export const BackgroundColor = "#17171A"
export const LinearGradientColorOne = "#70A2FF"
export const LinearGradientColorTwo = "#F76E64"
export const transparent = "rgba(0,0,0,0)"
export const bluetext = "#5F97FF"
export const graycolor = "#888DAA"
export const lightgray = "#E5E5E5"
export const green = "#76E268"