export const GET_NEWS = "GET_NEWS";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";

export const GET_NEWS_DETAILS = "GET_NEWS_DETAILS";
export const GET_NEWS_DETAILS_SUCCESS = "GET_NEWS_DETAILS_SUCCESS";

export const GET_USER = "GET_USER";                                 // 
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const GET_CAMPAIGN = "GET_CAMPAIGN";
export const GET_CAMPAIGN_SUCCESS = "GET_CAMPAIGN_SUCCESS";

export const GET_USER_LIST = "GET_USER_LIST";                     //
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";

export const CHECK_AVAILABILITY = "CHECK_AVAILABILITY";
export const CHECK_AVAILABILITY_SUCCESS = "CHECK_AVAILABILITY_SUCCESS";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const CREATE_BANNER = "CREATE_BANNER";
export const CREATE_BANNER_SUCCESS = "CREATE_BANNER_SUCCESS";

export const CREATE_COMPAIGN = "CREATE_COMPAIGN";
export const CREATE_COMPAIGN_SUCCESS = "CREATE_COMPAIGN_SUCCESS";

export const GET_BANNER = "GET_BANNER";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";

export const GET_BANNER_BY_ID = "GET_BANNER_BY_ID";                //           
export const GET_BANNER_BY_ID_SUCCESS = "GET_BANNER_BY_ID_SUCCESS";

export const GET_BANNER_BY_ID_1 = "GET_BANNER_BY_ID_1";                //           
export const GET_CAMPAIGN_BY_ID_1 = "GET_CAMPAIGN_BY_ID_1";                //           
